# main_wss.py
# 3D table tennis: the phone is the paddle (over WSS/TLS), MediaPipe places
# it in the frame, and the physics is our own.
#
# Requires: pip install panda3d websockets numpy
# Needs selfsigned.pem in this folder (generated by server.py).
#
# Run:
#   python server.py        # terminal 1: HTTPS static server :8443
#   python mp_sender.py     # terminal 2: webcam hand tracking -> UDP :5005
#   python main_wss.py      # terminal 3: the game + WSS :8766
#
# Changes from the previous version:
#   * All physics now comes from pingpong.physics (drag, Magnus, spin).
#     Bullet is gone -- the game and the offline solver share one model.
#   * Orientation goes through pingpong.quat.Calibration, fixing the three
#     stacked rotation bugs that made the paddle angle come out skewed.
#   * Swing power is derived from gyroscope angular velocity
#     (pingpong.swing) rather than double-integrated acceleration.
#   * Strokes are logged to strokes.csv with a schema that actually
#     contains the incoming ball state and spin.

import asyncio
import json
import math
import socket
import ssl
import threading
import time

import numpy as np
from direct.gui.OnscreenText import OnscreenText
from direct.showbase.ShowBase import ShowBase
from direct.task import Task
from panda3d.core import (
    AmbientLight,
    CardMaker,
    DirectionalLight,
    LineSegs,
    NodePath,
    PerspectiveLens,
    Quat,
    Spotlight,
    TextNode,
    TransparencyAttrib,
    Vec3,
    Vec4,
    WindowProperties,
    loadPrcFileData,
)
import websockets

from pingpong import constants as C
from pingpong import datalog, physics, quat, serve, stroke, swing

# ---------------------------------------------------------------- config
WSS_PORT = 8766
PEM_FILE = "selfsigned.pem"
PLAYER_IDS = ["P1"]
MP_UDP_ADDR = ("127.0.0.1", 5005)

# Depth (X) is assisted by the game. A phone has no position sensing, so
# the player owns timing, angle and swing strength, and the game handles
# how far forward the paddle sits.
PADDLE_READY_X = -1.30      # ready position
PADDLE_STRIKE_X = -1.12     # strike position

# Hand tracking -> paddle placement. These map the usable part of the camera
# frame onto the range the ball actually arrives in. Getting this wrong is
# what made placement feel uncontrollable: the first version sent the whole
# frame width to +/-1.0 m, wider than the table itself.
HAND_MARGIN = 0.18          # ignore this much of each frame edge
# The reachable range has to cover where balls actually arrive. Measured
# arrivals reach +/-0.72 m across the table, so at the old +/-0.55 some balls
# were literally unreachable even at full stretch.
HAND_Y_RANGE = 0.78
HAND_Z_LOW = C.TABLE_H + 0.00
HAND_Z_HIGH = C.TABLE_H + 0.55

# MediaPipe drops the hand for a frame or two very often. Hold the last good
# sample through gaps shorter than this instead of falling back to the
# keyboard, which is what used to make the paddle snap across the table.
MP_HOLD = 0.60
MP_SMOOTH_TAU = 0.06        # low-pass on the hand reading

# Effective capture radius of the blade. The drawn blade is 7.5 cm, but this
# is a game before it is a measurement rig, so the catch area is generous.
# Lower it toward 0.075 if you ever want the strict version.
HIT_RADIUS = 0.135

SERVE_INTERVAL = 2.0
RALLY_TIMEOUT = 6.0
# How long the ball keeps flying after the point is already decided. Cutting
# it on the frame it touches down makes a good shot disappear exactly when
# you want to watch where it went.
RALLY_LINGER = 1.1

# Display settings have to be applied before ShowBase starts up
loadPrcFileData("", "sync-video 1")
loadPrcFileData("", "clock-mode limited")
loadPrcFileData("", "clock-frame-rate 60")
loadPrcFileData("", "framebuffer-multisample 1")
loadPrcFileData("", "multisamples 4")
loadPrcFileData("", "textures-power-2 none")


# ================================================================ phone
class PhoneState:
    """Latest sensor state for one phone, plus derived quantities."""

    def __init__(self):
        self.q = np.array([0.0, 0.0, 0.0, 1.0])
        self.gyro = np.zeros(3)
        self.acc = np.zeros(3)
        self.acc_includes_g = False
        self.last_t = 0.0

        self.calib = quat.Calibration()
        self.swing = swing.SwingEstimator()
        self.paddle_quat = quat.NEUTRAL_PADDLE.copy()
        self.paddle_vel = np.zeros(3)
        self.swing_speed = 0.0

    @property
    def connected(self):
        return (time.time() - self.last_t) < 2.0

    @property
    def ready(self):
        return self.connected and self.calib.ready


class PhoneHub:
    def __init__(self):
        self.clients = {}
        self.states = {p: PhoneState() for p in PLAYER_IDS}
        self._i = 0

    def assign(self, ws):
        pid = PLAYER_IDS[self._i % len(PLAYER_IDS)]
        self._i += 1
        self.clients[ws] = pid
        print(f"[WSS] assigned {pid}")
        return pid

    def remove(self, ws):
        pid = self.clients.pop(ws, None)
        if pid:
            print(f"[WSS] {pid} disconnected")

    def update(self, pid, data):
        st = self.states[pid]
        typ = data.get("type")
        now = time.time()

        if typ == "imu":
            # controller.html now packs orientation, gyro and accelerometer
            # into a single message so the samples line up in time.
            q = data.get("q")
            if q and len(q) == 4:
                st.q = np.asarray(q, dtype=float)
            g = data.get("gyro")
            if g and len(g) == 3:
                st.gyro = np.asarray(g, dtype=float)
            a = data.get("acc")
            if a and len(a) == 3:
                st.acc = np.asarray(a, dtype=float)
            st.acc_includes_g = bool(data.get("accg", False))

        elif typ == "ori_q":                       # legacy format
            q = data.get("q") or [0, 0, 0, 1]
            st.q = np.asarray(q, dtype=float)

        elif typ in ("linacc", "linacc_est", "acc_incl_g"):
            a = data.get("acc") or {}
            st.acc = np.array([
                float(a.get("x") or 0), float(a.get("y") or 0), float(a.get("z") or 0)
            ])
            st.acc_includes_g = (typ == "acc_incl_g")

        elif typ in ("center", "calib"):
            st.calib.calibrate(st.q)
            st.swing.reset()
            print(f"[WSS] {pid} calibrated")

        st.last_t = now

        # Orientation -> paddle pose; gyroscope -> swing velocity
        if st.calib.ready:
            st.paddle_quat = st.calib.paddle_quat(st.q)
            sample = st.swing.update(
                now, st.gyro, st.acc, st.q, st.calib,
                accel_includes_gravity=st.acc_includes_g,
            )
            st.paddle_vel = sample.velocity
            st.swing_speed = sample.speed


hub = PhoneHub()


async def ws_handler(ws):
    pid = hub.assign(ws)
    await ws.send(json.dumps({"hello": "ok", "assigned": pid}))
    try:
        async for msg in ws:
            try:
                hub.update(pid, json.loads(msg))
            except Exception as e:
                print("[WSS] parse error:", e)
    finally:
        hub.remove(ws)


def launch_wss():
    async def main():
        ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        ctx.load_cert_chain(PEM_FILE, PEM_FILE)
        async with websockets.serve(ws_handler, "0.0.0.0", WSS_PORT, ssl=ctx):
            print(f"[WSS] listening on wss://0.0.0.0:{WSS_PORT}")
            await asyncio.Future()

    threading.Thread(target=lambda: asyncio.run(main()), daemon=True).start()


# ================================================================ HUD stub
class _HudStub:
    """Stands in for OnscreenText when headless, so game logic needs no branches."""

    def setText(self, *_a, **_kw):
        pass

    def show(self):
        pass

    def hide(self):
        pass


# ================================================================ game
class Game(ShowBase):
    def __init__(self):
        super().__init__()

        # Headless mode is loadPrcFileData("", "window-type none"), where
        # self.win is None. Supporting it is not only for tests: headless
        # self-play for training data will run through this same path.
        self.headless = self.win is None

        if not self.headless:
            # In offscreen mode self.win is a GraphicsBuffer with no
            # request_properties
            if hasattr(self.win, "request_properties"):
                props = WindowProperties()
                props.setTitle("3D Ping-Pong - phone paddle + physics")
                self.win.request_properties(props)
            self.disableMouse()
            self.set_background_color(0.04, 0.05, 0.07, 1)

        # ---- MediaPipe UDP ----
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            self.sock.bind(MP_UDP_ADDR)
        except OSError as e:
            print(f"[WARN] could not bind MediaPipe UDP {MP_UDP_ADDR}: {e}")
        self.sock.setblocking(False)
        self.mp_pos = np.array([0.5, 0.5, 0.0])     # smoothed
        self.mp_raw = np.array([0.5, 0.5, 0.0])     # newest packet
        self.mp_active = False
        self.mp_last_t = 0.0

        # ---- camera ----
        if not self.headless:
            self.camLens.set_fov(58)
            self.camLens.set_near(0.05)
            self.camera.set_pos(-3.15, 0.0, C.TABLE_H + 1.05)
            self.camera.look_at(0.2, 0.0, C.TABLE_H + 0.12)

        self._build_scene()
        self._build_hud()

        # ---- physics ----
        self.ball = physics.BallWorld()
        self.paddle_home = np.array([PADDLE_READY_X, 0.0, C.TABLE_H + 0.25])
        home = self.paddle_home
        self.paddle = physics.Paddle(pos=home.copy(),
                                     normal=np.array([1.0, 0.0, 0.0]))
        self.last_hit_time = 0.0

        # Separates stance from swing. Without this the paddle follows the
        # hand through the whole stroke and thrashes across the table.
        self.stroke = stroke.StrokeController(stroke.StrokeConfig(), home=home)
        self.contact = None            # predicted ball arrival at the strike plane
        self._contact_cache = None
        self._contact_time = 0.0
        self._contact_stale = True
        self._manual_swing_until = 0.0
        self._manual_swing_decay = 0.0

        # ---- rally state ----
        self.serve_pos = np.zeros(3)
        self.serve_vel = np.zeros(3)
        self.serve_spin = np.zeros(3)
        self.player_hit = False
        self.rally_over_at = 0.0
        self.last_serve_time = time.time() - SERVE_INTERVAL
        self.score_player = 0
        self.score_cpu = 0
        self.last_result_text = ""

        # ---- data logging ----
        self.logger = datalog.StrokeLogger("strokes.csv", source=datalog.SRC_HUMAN)

        # ---- keyboard (fallback when there is no MediaPipe / phone) ----
        self.keys = {}
        for k in ("arrow_left", "arrow_right", "arrow_up", "arrow_down"):
            self.accept(k, self._set_key, [k, True])
            self.accept(k + "-up", self._set_key, [k, False])
        self.accept("r", self.serve_ball)
        self.accept("space", self.manual_swing)
        # Mouse click swings too. Keyboard events need the window to have
        # focus, which is easy to lose to the terminal behind it, and a click
        # both takes the focus back and plays the stroke.
        self.accept("mouse1", self.manual_swing)
        self.accept("f1", self.toggle_help)
        self.kb_y = 0.0
        self.kb_z = 0.0

        self.ball_visual_quat = Quat()
        self.last_time = time.time()
        self.taskMgr.add(self.update, "update")

        print(f"[INFO] open controller.html on your phone -> wss://<PC-IP>:{WSS_PORT}")
        print("[INFO] press Calibrate first, or the paddle will not move.")

    def _set_key(self, key, value):
        self.keys[key] = value

    # ------------------------------------------------------------ scene
    def _build_scene(self):
        """Build the visible geometry.

        The old version left Bullet's debug wireframe switched on
        (dbg_np.show()); those lines were most of what you saw on screen.
        There is no collision debug visualisation to draw any more.
        """
        render = self.render

        # ---- lights: ambient + key directional + shadow-casting spot ----
        amb = AmbientLight("amb")
        amb.set_color(Vec4(0.32, 0.34, 0.40, 1))
        render.set_light(render.attach_new_node(amb))

        key = DirectionalLight("key")
        key.set_color(Vec4(0.55, 0.55, 0.58, 1))
        knp = render.attach_new_node(key)
        knp.set_hpr(40, -55, 0)
        render.set_light(knp)

        spot = Spotlight("spot")
        spot.set_color(Vec4(0.95, 0.93, 0.88, 1))
        lens = PerspectiveLens()
        lens.set_fov(70)
        lens.set_near_far(1.0, 12.0)
        spot.set_lens(lens)
        # The ground shadow is not just decoration: it is the main cue the
        # player has for judging ball depth.
        spot.set_shadow_caster(True, 2048, 2048)
        spot.set_attenuation(Vec3(1, 0, 0))
        snp = render.attach_new_node(spot)
        snp.set_pos(0.0, 0.0, 3.6)
        snp.look_at(0, 0, C.TABLE_H)
        render.set_light(snp)

        # Auto shader gives per-pixel lighting and shadows
        render.set_shader_auto()

        # ---- room, so nothing floats in a void ----
        room = self._make_card(8.0, 8.0)
        room.reparent_to(render)
        room.set_p(-90)
        room.set_pos(0, 0, 0)
        room.set_color(0.11, 0.12, 0.15, 1)

        for hpr, pos in (((0, 0, 0), (0, 4.0, 2.0)), ((180, 0, 0), (0, -4.0, 2.0))):
            wall = self._make_card(8.0, 4.0)
            wall.reparent_to(render)
            wall.set_hpr(*hpr)
            wall.set_pos(*pos)
            wall.set_color(0.08, 0.09, 0.12, 1)

        back = self._make_card(8.0, 4.0)
        back.reparent_to(render)
        back.set_hpr(-90, 0, 0)
        back.set_pos(3.4, 0, 2.0)
        back.set_color(0.07, 0.08, 0.11, 1)

        # ---- table ----
        self.table_np = render.attach_new_node("table")

        top = self._make_card(C.TABLE_L, C.TABLE_W)
        top.reparent_to(self.table_np)
        top.set_p(-90)
        top.set_pos(0, 0, C.TABLE_H)
        top.set_color(0.06, 0.24, 0.45, 1)

        # White court lines
        lines = LineSegs("table_lines")
        lines.set_thickness(2.5)
        lines.set_color(0.95, 0.95, 0.95, 1)
        hx, hy, z = C.TABLE_L / 2, C.TABLE_W / 2, C.TABLE_H + 0.002
        for a, b in (
            ((-hx, -hy), (hx, -hy)), ((hx, -hy), (hx, hy)),
            ((hx, hy), (-hx, hy)), ((-hx, hy), (-hx, -hy)),
            ((-hx, 0.0), (hx, 0.0)),          # centre line
        ):
            lines.move_to(a[0], a[1], z)
            lines.draw_to(b[0], b[1], z)
        self.table_np.attach_new_node(lines.create())

        # Apron and legs
        for sx in (-1, 1):
            side = self._make_card(C.TABLE_L, 0.06)
            side.reparent_to(self.table_np)
            side.set_pos(0, sx * hy, C.TABLE_H - 0.03)
            side.set_h(0 if sx > 0 else 180)
            side.set_color(0.03, 0.12, 0.26, 1)
        for sx in (-1, 1):
            for sy in (-1, 1):
                leg = self._make_card(0.07, C.TABLE_H)
                leg.reparent_to(self.table_np)
                leg.set_pos(sx * (hx - 0.18), sy * (hy - 0.10), C.TABLE_H / 2)
                leg.set_color(0.10, 0.10, 0.12, 1)

        # ---- net ----
        net = self.render.attach_new_node("net")
        mesh = LineSegs("net_mesh")
        mesh.set_thickness(1.2)
        mesh.set_color(0.85, 0.87, 0.92, 0.55)
        span = C.TABLE_W / 2 + C.NET_OVERHANG
        n_cols = 26
        for i in range(n_cols + 1):
            y = -span + 2 * span * i / n_cols
            mesh.move_to(0, y, C.TABLE_H)
            mesh.draw_to(0, y, C.NET_TOP_Z)
        n_rows = 6
        for j in range(n_rows + 1):
            z = C.TABLE_H + C.NET_H * j / n_rows
            mesh.move_to(0, -span, z)
            mesh.draw_to(0, span, z)
        net_np = net.attach_new_node(mesh.create())
        net_np.set_transparency(TransparencyAttrib.M_alpha)
        # White tape along the top
        band = LineSegs("net_band")
        band.set_thickness(4.0)
        band.set_color(1, 1, 1, 1)
        band.move_to(0, -span, C.NET_TOP_Z)
        band.draw_to(0, span, C.NET_TOP_Z)
        net.attach_new_node(band.create())

        # ---- paddle: red rubber / black rubber + wooden handle ----
        self.paddle_np = render.attach_new_node("paddle")
        face_r = self._make_card(0.15, 0.16)
        face_r.reparent_to(self.paddle_np)
        face_r.set_pos(0, 0.004, 0)
        face_r.set_color(0.80, 0.13, 0.13, 1)
        face_b = self._make_card(0.15, 0.16)
        face_b.reparent_to(self.paddle_np)
        face_b.set_h(180)
        face_b.set_pos(0, -0.004, 0)
        face_b.set_color(0.09, 0.09, 0.10, 1)
        edge = self._make_card(0.15, 0.16)
        edge.reparent_to(self.paddle_np)
        edge.set_p(90)
        edge.set_color(0.85, 0.75, 0.55, 1)
        edge.set_scale(1.02)
        handle = self._make_card(0.035, 0.11)
        handle.reparent_to(self.paddle_np)
        handle.set_pos(0, 0, -0.135)
        handle.set_color(0.42, 0.28, 0.16, 1)

        # Face-normal indicator, so the current blade angle is readable
        norm_seg = LineSegs("paddle_normal")
        norm_seg.set_thickness(2.0)
        norm_seg.set_color(0.3, 0.9, 1.0, 0.9)
        norm_seg.move_to(0, 0, 0)
        norm_seg.draw_to(0, 0.22, 0)
        self.paddle_np.attach_new_node(norm_seg.create())

        # ---- ball ----
        self.ball_np = render.attach_new_node("ball")
        self.ball_visual = self.ball_np.attach_new_node("ball_visual")
        sphere = self.loader.load_model("models/misc/sphere")
        sphere.reparent_to(self.ball_visual)
        sphere.set_scale(C.BALL_RADIUS)
        sphere.set_color(0.98, 0.95, 0.55, 1)
        # Two coloured dots make the spin direction and rate visible
        for sign in (1, -1):
            dot = self.loader.load_model("models/misc/sphere")
            dot.reparent_to(self.ball_visual)
            dot.set_scale(C.BALL_RADIUS * 0.42)
            dot.set_pos(0, 0, sign * C.BALL_RADIUS * 0.86)
            dot.set_color(0.85, 0.35, 0.10, 1)

        # ---- timing ring ----
        # The player cannot feel the ball, so the swing cue has to be visual.
        # This ring sits where the ball will cross the strike plane and
        # shrinks as that moment approaches: smallest means swing now.
        ring = LineSegs("timing_ring")
        ring.set_thickness(5.0)
        ring.set_color(0.35, 0.95, 1.0, 1.0)
        steps = 44
        for i in range(steps + 1):
            a = 2 * math.pi * i / steps
            (ring.move_to if i == 0 else ring.draw_to)(0, math.cos(a), math.sin(a))
        # Cross-hairs so the centre is readable when the ring is small
        for dy, dz in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            ring.move_to(0, dy * 0.55, dz * 0.55)
            ring.draw_to(0, dy * 0.95, dz * 0.95)
        self.ring_np = render.attach_new_node(ring.create())
        self.ring_np.set_transparency(TransparencyAttrib.M_alpha)
        self.ring_np.set_light_off()
        self.ring_np.hide()

        # ---- predicted trajectory + ball shadow ----
        self.traj_np = None
        self.shadow_np = self._make_card(0.055, 0.055)
        self.shadow_np.reparent_to(render)
        self.shadow_np.set_p(-90)
        self.shadow_np.set_color(0, 0, 0, 0.32)
        self.shadow_np.set_transparency(TransparencyAttrib.M_alpha)
        self.shadow_np.set_light_off()

    def _make_card(self, width, height):
        cm = CardMaker("card")
        cm.set_frame(-width / 2, width / 2, -height / 2, height / 2)
        np_ = NodePath(cm.generate())
        np_.set_two_sided(True)
        return np_

    # ------------------------------------------------------------ HUD
    def hud_text(self, pos, scale=0.045, align=TextNode.ALeft,
                 fg=(1, 1, 1, 1), text="", corner="topleft"):
        """Create a HUD text node; returns a no-op stub when headless.

        coach_game uses this too, so neither has to special-case headless.
        """
        if self.headless:
            return _HudStub()
        parent = {"topleft": self.a2dTopLeft,
                  "bottomleft": self.a2dBottomLeft,
                  }.get(corner, self.a2dBottomCenter)
        return OnscreenText(
            text=text, pos=pos, scale=scale, fg=fg,
            shadow=(0, 0, 0, 0.65), align=align, mayChange=True,
            parent=parent,
        )

    def _build_hud(self):
        self.hud_score = self.hud_text((0.06, -0.12), 0.075)
        self.hud_state = self.hud_text((0.06, -0.22), 0.045)
        self.hud_ball = self.hud_text((0.06, -0.30), 0.040)
        self.hud_spin = self.hud_text((0.06, -0.36), 0.040)
        self.hud_swing = self.hud_text((0.06, -0.42), 0.040)
        self.hud_conn = self.hud_text((0.06, -0.50), 0.038)

        self.hud_help = self.hud_text(
            (0, 0.10), 0.038, TextNode.ACenter, (0.85, 0.9, 1, 1),
            text=("[F1] help   [R] re-serve   [Space] manual swing   "
                  "[Arrows] move paddle\n"
                  "Phone: after Calibrate, rotating sets the blade angle and "
                  "swinging sets power and spin\n"
                  "Depth is assisted by the game - you own timing, angle and "
                  "swing strength"),
            corner="bottom",
        )
        self.help_visible = True

    def toggle_help(self):
        self.help_visible = not self.help_visible
        (self.hud_help.show if self.help_visible else self.hud_help.hide)()

    # ------------------------------------------------------------ serve
    def serve_ball(self):
        """The computer serves from its half onto ours, with random spin."""
        if self.logger.has_pending:
            self.logger.commit(None, datalog.RESULT_MISS)
        self.logger.new_rally()

        rng = np.random.default_rng()
        start = np.array([
            rng.uniform(0.75, 1.15),
            rng.uniform(-0.45, 0.45),
            C.TABLE_H + rng.uniform(0.16, 0.30),
        ])
        target = np.array([
            rng.uniform(-1.05, -0.42),
            # Narrower than it looks: the ball keeps drifting sideways after
            # the bounce, so a +/-0.50 target spreads arrivals out to +/-0.72
            rng.uniform(-0.34, 0.34),
            C.TABLE_TOP_Z + C.BALL_RADIUS,
        ])
        # Serve spin: a random mix of top, back and side
        spin = np.array([
            rng.uniform(-40, 40),
            rng.uniform(-120, 90),
            rng.uniform(-60, 60),
        ])
        # Flight time sets how flat the serve is. At 0.55-0.80 s over a ~2 m
        # gap the solver had to loft the ball to keep it airborne that long,
        # so serves arrived as slow lobs at under 2 m/s. Shorter means flatter
        # and faster, which is both more like table tennis and much less dead
        # time between rallies.
        flight = rng.uniform(0.32, 0.46)
        vel = serve.solve_serve(start, target, flight, spin)

        self.ball.reset(start, vel, spin)
        self.invalidate_contact()
        self.stroke.reset()
        self.serve_pos = start.copy()
        self.serve_vel = vel.copy()
        self.serve_spin = spin.copy()
        self.player_hit = False
        self.rally_over_at = 0.0
        self.last_serve_time = time.time()
        self._clear_traj()

    def manual_swing(self):
        """Space bar: play a stroke with no phone attached.

        Holds the swing flag on briefly so StrokeController sees a rising
        edge and lays out an arc, exactly as a real swing would.
        """
        st = hub.states["P1"]
        st.paddle_vel = np.array([7.0, 0.0, 3.0])
        st.swing_speed = float(np.linalg.norm(st.paddle_vel))
        self._manual_swing_until = time.time() + 0.12
        self._manual_swing_decay = self._manual_swing_until + 0.30
        # Printed so a swing is verifiable from the terminal even if the
        # window is not where you are looking
        c = self.contact
        print("[SWING] manual" + (f"  contact in {c.time * 1000:.0f} ms"
                                  if c is not None else "  no ball incoming"))

    # ------------------------------------------------------------ input
    def _read_mediapipe(self, dt=0.0):
        """Read the newest hand sample, riding out short tracking dropouts.

        MediaPipe loses the hand constantly during play -- fast motion, motion
        blur, the hand clipping the frame edge. Previously a dropout made this
        return False, the caller fell through to the keyboard branch, and the
        paddle snapped to wherever the keyboard offset happened to be and back
        again a few frames later. That is the "paddle flies around" problem.

        Now the last good sample is held through the gap, and the reading is
        low-passed so the jitter that survives does not reach the paddle.
        """
        got = False
        try:
            while True:
                data, _ = self.sock.recvfrom(1024)
                raw = json.loads(data.decode())
                self.mp_raw = np.array([
                    float(raw.get("x", 0.5)),
                    float(raw.get("y", 0.5)),
                    float(raw.get("z", 0.0)),
                ])
                got = True
        except (BlockingIOError, OSError, ValueError, json.JSONDecodeError):
            pass

        now = time.time()
        if got:
            if not self.mp_active:
                self.mp_pos = self.mp_raw.copy()      # first sample: no easing
                self.mp_active = True
            self.mp_last_t = now
        elif self.mp_active and (now - self.mp_last_t) > MP_HOLD:
            self.mp_active = False                     # really gone now

        if self.mp_active and dt > 0.0:
            alpha = 1.0 - math.exp(-dt / MP_SMOOTH_TAU)
            self.mp_pos = self.mp_pos + (self.mp_raw - self.mp_pos) * alpha
        return self.mp_active

    def _hand_position(self, dt):
        """Where hand tracking says the paddle should be.

        This is the player's placement; pingpong.stroke's aim assist only
        refines it.

        The mapping matters more than it looks. The first version sent the
        full camera width to +/-1.0 m -- wider than the table -- so a small
        hand movement threw the paddle right across it and nothing felt
        controllable. Here the usable part of the frame maps onto the range
        the ball actually arrives in, and the outer margin is ignored because
        hands rarely reach the frame edges anyway.
        """
        if self._read_mediapipe(dt):
            def span(v, lo, hi):
                t = (float(np.clip(v, HAND_MARGIN, 1.0 - HAND_MARGIN)) - HAND_MARGIN)
                t /= (1.0 - 2.0 * HAND_MARGIN)
                return lo + (hi - lo) * t

            # mp_sender already mirrors the frame, so hand-right is paddle-right
            y = span(self.mp_pos[0], HAND_Y_RANGE, -HAND_Y_RANGE)
            z = span(self.mp_pos[1], HAND_Z_HIGH, HAND_Z_LOW)
        else:
            speed = 1.1 * dt
            self.kb_y += (self.keys.get("arrow_left", False) - self.keys.get("arrow_right", False)) * speed
            self.kb_z += (self.keys.get("arrow_up", False) - self.keys.get("arrow_down", False)) * speed
            self.kb_y = float(np.clip(self.kb_y, -1.0, 1.0))
            self.kb_z = float(np.clip(self.kb_z, -1.0, 1.0))
            y = self.kb_y * HAND_Y_RANGE
            z = (HAND_Z_LOW + HAND_Z_HIGH) / 2 + self.kb_z * (HAND_Z_HIGH - HAND_Z_LOW) / 2

        return np.array([PADDLE_READY_X, y, z])

    # The prediction costs several milliseconds, so it is refreshed at this
    # rate rather than every frame, with the countdown ticked down in
    # between. Any bounce invalidates it immediately -- the ball's path
    # changes completely there.
    CONTACT_REFRESH = 1.0 / 25.0

    def invalidate_contact(self):
        self._contact_stale = True

    def predict_contact(self, now=None, dt=0.0):
        """Predicted ball arrival at the strike plane, or None."""
        if not self.ball.active:
            self._contact_cache = None
            return None

        now = time.time() if now is None else now
        fresh = (
            self._contact_stale
            or self._contact_cache is None
            or (now - self._contact_time) >= self.CONTACT_REFRESH
        )
        if fresh:
            self._contact_cache = physics.predict_plane_crossing(
                self.ball.pos, self.ball.vel, self.ball.spin, PADDLE_STRIKE_X
            )
            self._contact_time = now
            self._contact_stale = False
        elif self._contact_cache is not None:
            self._contact_cache.time = max(0.0, self._contact_cache.time - dt)
        return self._contact_cache

    def _control_paddle(self, st, dt):
        """Apply player input to the paddle.

        CoachGame overrides this to let the AI take over, so extending the
        game does not require touching this file. (The old coach_game
        monkey-patched update(), which was fragile.)
        """
        now = time.time()

        # A keyboard swing is a one-shot, so its velocity has to expire.
        # Without this the HUD reported a permanent 7.6 m/s swing and every
        # later contact used it.
        if not st.connected and self._manual_swing_decay and now > self._manual_swing_decay:
            st.paddle_vel = np.zeros(3)
            st.swing_speed = 0.0
            self._manual_swing_decay = 0.0

        hand = self._hand_position(dt)

        # Hand places the paddle, aim assist refines it, and a detected swing
        # plays a real backswing / sweep / follow-through through that point
        swinging = st.swing.swinging or now < self._manual_swing_until
        self.paddle.pos = self.stroke.update(
            now, dt, hand, swinging, st.paddle_vel, self.contact
        )

        if st.calib.ready:
            pq = st.paddle_quat
            self.paddle.normal = quat.rotate(pq, [0.0, 1.0, 0.0])
            # Swing velocity comes from the gyroscope (v = w x r), not from
            # differentiating position
            self.paddle.velocity = st.paddle_vel
        else:
            pq = quat.NEUTRAL_PADDLE
            self.paddle.normal = np.array([1.0, 0.0, 0.0])
            self.paddle.velocity = st.paddle_vel

        self.apply_paddle_transform(pq)

    def apply_paddle_transform(self, paddle_quat):
        """Push the physics paddle pose onto the visible node."""
        self.paddle_np.set_quat(Quat(*quat.to_panda(paddle_quat)))
        self.paddle_np.set_pos(*self.paddle.pos)

    # ------------------------------------------------------------ contact
    def _contact_allowed(self):
        """Whether the paddle can strike right now.

        Overridden by CoachGame, which drives the paddle directly instead of
        through the swing state machine.
        """
        return self.stroke.state in (stroke.FORWARD, stroke.FOLLOW)

    def _try_hit(self, now, ball_prev, paddle_prev):
        """Detect the ball crossing the blade and apply the collision.

        Contact only counts while the paddle is actually being swung forward.
        Without this, the paddle tracking the ball would return it on its own
        and there would be no game left -- timing is the whole point.
        """
        if not self.ball.active or (now - self.last_hit_time) < 0.15:
            return
        if not self._contact_allowed():
            return

        n = self.paddle.face_normal_toward(ball_prev)
        t = physics.swept_blade_hit(ball_prev, self.ball.pos,
                                    paddle_prev, self.paddle.pos,
                                    n, HIT_RADIUS)
        if t is None:
            return

        # Rewind the ball to the contact point so the bounce starts from the
        # blade rather than from wherever the frame happened to end
        self.ball.pos = ball_prev + (self.ball.pos - ball_prev) * t

        in_vel = self.ball.vel.copy()
        in_spin = self.ball.spin.copy()
        in_pos = self.ball.pos.copy()

        # n was chosen from ball_prev, before the ball was rewound onto the
        # blade -- the only point at which the face is unambiguous
        out_vel, out_spin = physics.hit_with_paddle(
            in_vel, in_spin, self.paddle, self.ball.pos, normal=n
        )
        self.ball.vel = out_vel
        self.ball.spin = out_spin
        # Push clear of the blade so the same frame cannot retrigger
        self.ball.pos = self.ball.pos + n * (C.BALL_RADIUS * 1.6)
        self.ball.bounces = 0
        self.ball.bounce_side = []
        self.last_hit_time = now
        self.player_hit = True
        self.invalidate_contact()

        # Predict the landing point for the HUD and the log
        pred = physics.simulate(self.ball.pos, out_vel, out_spin, max_time=3.0)

        self.logger.pending(datalog.StrokeRecord(
            t=now,
            # Whoever owns the logger owns the label. Hardcoding SRC_HUMAN
            # here wrote the AI's own strokes into the human dataset.
            source=self.logger.source,
            in_pos=in_pos, in_vel=in_vel, in_spin=in_spin,
            serve_pos=self.serve_pos, serve_vel=self.serve_vel,
            paddle_pos=self.paddle.pos.copy(),
            paddle_normal=n.copy(),
            paddle_vel=self.paddle.velocity.copy(),
            out_vel=out_vel.copy(), out_spin=out_spin.copy(),
        ))
        self._draw_traj(pred.trajectory)
        print(f"[HIT] |v|={np.linalg.norm(out_vel):5.2f} m/s  "
              f"spin={np.linalg.norm(out_spin):6.1f} rad/s  "
              f"swing={np.linalg.norm(self.paddle.velocity):4.1f} m/s")

    # ------------------------------------------------------------ scoring
    def end_rally(self, linger=None):
        """Stop the rally, but let the ball keep flying for a moment.

        Killing the ball on the frame it touches down makes a good shot
        vanish exactly when you want to see where it went. It keeps
        travelling and bouncing normally; only the scoring is already
        decided.
        """
        self.rally_over_at = time.time() + (RALLY_LINGER if linger is None else linger)

    def _resolve(self, event, pos):
        """Score the rally once the ball lands, goes out or hits the net."""
        if self.rally_over_at:            # already decided; just watching it out
            return
        if event == "bounce":
            side = "own" if pos[0] < 0 else "opponent"
            if self.player_hit and side == "opponent":
                self._score(True, "Point! Landed on their half")
                self.logger.commit(pos, datalog.RESULT_IN, bounces=1)
                self.end_rally()
            elif self.player_hit and side == "own":
                self._score(False, "Did not clear the net")
                self.logger.commit(pos, datalog.RESULT_OWN_SIDE)
                self.end_rally()
            elif not self.player_hit and side == "own" and self.ball.bounces >= 2:
                self._score(False, "Missed it")
                self.logger.commit(None, datalog.RESULT_MISS)
                self.end_rally()
        elif event == "net":
            if self.player_hit:
                self._score(False, "Into the net")
                self.logger.commit(pos, datalog.RESULT_NET)
                self.end_rally()
        elif event == "out":
            if self.player_hit:
                self._score(False, "Out")
                self.logger.commit(pos, datalog.RESULT_OUT)
            else:
                self._score(False, "Missed it")
                self.logger.commit(None, datalog.RESULT_MISS)
            # Already off the table, so nothing left worth watching
            self.ball.active = False
            self.rally_over_at = 0.0

    def _score(self, player_point, text):
        if player_point:
            self.score_player += 1
        else:
            self.score_cpu += 1
        self.last_result_text = text

    # ------------------------------------------------------------ visuals
    def _clear_traj(self):
        if self.traj_np is not None:
            self.traj_np.remove_node()
            self.traj_np = None

    def _draw_traj(self, pts):
        self._clear_traj()
        if pts is None or len(pts) < 2:
            return
        segs = LineSegs("traj")
        segs.set_thickness(2.5)
        segs.set_color(1.0, 0.85, 0.25, 0.85)
        segs.move_to(*pts[0])
        for p in pts[1:]:
            segs.draw_to(*p)
        self.traj_np = self.render.attach_new_node(segs.create())
        self.traj_np.set_transparency(TransparencyAttrib.M_alpha)
        self.traj_np.set_light_off()

    # Ring radius at the far end of the cue and at the moment of contact.
    RING_MAX_R, RING_MIN_R = 0.26, 0.055
    RING_LEAD = 0.65          # seconds of warning the cue gives

    def _update_timing_ring(self):
        """Ring size counts down to contact; ring colour shows aim lock.

        Two separate things the player needs to know: *when* to swing, and
        whether they are standing close enough for the assist to reach.
        Size carries the first, colour the second.
        """
        c = self.contact
        if c is None or self.stroke.busy or not self.ball.active:
            self.ring_np.hide()
            return
        f = float(np.clip(c.time / self.RING_LEAD, 0.0, 1.0))
        r = self.RING_MIN_R + (self.RING_MAX_R - self.RING_MIN_R) * f
        self.ring_np.set_pos(PADDLE_STRIKE_X, c.pos[1], c.pos[2])
        self.ring_np.set_scale(r)

        # Green when the assist can reach you, red when you are out of range.
        # Kept fully opaque -- a fading cue is exactly the thing you stop
        # noticing while concentrating on the ball.
        w = self.stroke.last_aim_weight
        self.ring_np.set_color(1.0 - 0.9 * w, 0.18 + 0.82 * w, 0.22 + 0.18 * w, 1.0)
        self.ring_np.show()

    def _spin_visual(self, dt):
        """Rotate the ball model by its angular velocity so spin is visible."""
        w = self.ball.spin
        mag = float(np.linalg.norm(w))
        if mag < 1e-6:
            return
        axis = w / mag
        dq = Quat()
        dq.set_from_axis_angle_rad(mag * dt, Vec3(*axis))
        self.ball_visual_quat = dq * self.ball_visual_quat
        self.ball_visual_quat.normalize()
        self.ball_visual.set_quat(self.ball_visual_quat)

    def _update_hud(self, st):
        self.hud_score.setText(f"You {self.score_player}  -  CPU {self.score_cpu}")
        self.hud_state.setText(self.last_result_text)

        if self.ball.active:
            speed = float(np.linalg.norm(self.ball.vel))
            self.hud_ball.setText(f"Ball {speed * 3.6:5.1f} km/h  ({speed:4.1f} m/s)")
            spin = self.ball.spin
            rpm = float(np.linalg.norm(spin)) * 60 / (2 * math.pi)
            kind = "topspin" if spin[1] > 30 else ("backspin" if spin[1] < -30 else "flat")
            self.hud_spin.setText(f"Spin {rpm:5.0f} rpm  {kind}")
        else:
            self.hud_ball.setText("")
            self.hud_spin.setText("")

        swing_txt = f"Swing {st.swing_speed:4.1f} m/s"
        if self.stroke.busy:
            phase = {stroke.BACKSWING: "backswing",
                     stroke.FORWARD: "swinging",
                     stroke.FOLLOW: "follow-through"}
            swing_txt += f"   [{phase.get(self.stroke.state, self.stroke.state)}]"
            if not self.stroke.connected:
                swing_txt += "   too early"
        elif self.contact is not None:
            w = self.stroke.last_aim_weight
            lock = "on target" if w > 0.85 else (
                "close" if w > 0.0 else "out of reach")
            swing_txt += f"   ball in {self.contact.time:.2f} s   [{lock}]"
        self.hud_swing.setText(swing_txt)

        parts = ["Phone connected" if st.connected else "Phone offline"]
        if st.connected and not st.calib.ready:
            parts.append("not calibrated")
        parts.append("MediaPipe on" if self.mp_active else "MediaPipe off (arrow keys)")
        self.hud_conn.setText("   ".join(parts))

    # ------------------------------------------------------------ main loop
    def update(self, task: Task):
        now = time.time()
        dt = min(1.0 / 30.0, max(1e-4, now - self.last_time))
        self.last_time = now

        st = hub.states["P1"]

        # Predicted ball arrival at the strike plane. Resolved once per frame
        # because the swing controller, the timing ring and the AI coach all
        # need to be aiming at the same instant.
        self.contact = self.predict_contact(now, dt)

        # ---- paddle pose and position ----
        paddle_prev = self.paddle.pos.copy()
        self._control_paddle(st, dt)

        # ---- physics ----
        # The ball moves first, then contact is tested across the segment it
        # travelled. Testing before the move only ever saw single points and
        # let fast balls tunnel through the blade.
        ball_prev = self.ball.pos.copy()
        if self.ball.active:
            for event, pos in self.ball.advance(dt):
                # A bounce or a net clip changes the path completely, so the
                # cached prediction has to be thrown away
                self.invalidate_contact()
                self._resolve(event, pos)
            self._spin_visual(dt)

        # ---- contact ----
        self._try_hit(now, ball_prev, paddle_prev)

        # ---- ball and shadow ----
        # Hide with hide()/show(), never with a zero scale: a zero scale makes
        # the transform singular and Panda3D aborts the render with
        # "Assertion failed: has_mat()".
        self.ball_np.set_pos(*self.ball.pos)
        if self.ball.active:
            self.ball_np.show()
        else:
            self.ball_np.hide()

        if self.ball.active and self.ball.pos[2] > C.TABLE_H:
            on_table = (abs(self.ball.pos[0]) < C.TABLE_L / 2
                        and abs(self.ball.pos[1]) < C.TABLE_W / 2)
            sz = C.TABLE_H + 0.004 if on_table else 0.006
            self.shadow_np.set_pos(self.ball.pos[0], self.ball.pos[1], sz)
            self.shadow_np.show()
        else:
            self.shadow_np.hide()

        self._update_timing_ring()

        # ---- rally management ----
        # The point is already scored; the ball is just being watched out
        if self.rally_over_at and now > self.rally_over_at:
            self.ball.active = False
            self.rally_over_at = 0.0

        if self.ball.active and (now - self.last_serve_time) > RALLY_TIMEOUT:
            self.ball.active = False
            self.rally_over_at = 0.0
            if self.logger.has_pending:
                self.logger.commit(None, datalog.RESULT_MISS)
        if not self.ball.active and (now - self.last_serve_time) > SERVE_INTERVAL:
            self.serve_ball()

        self._update_hud(st)
        return Task.cont


# ---------------------------------------------------------------- entry
if __name__ == "__main__":
    launch_wss()
    Game().run()
